version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/fylr
    steps:
      - checkout
      - run: make ensure
      - run: make
      - run: make vet
      - run: make test
workflows:
  version: 2
  build-and-test:
    jobs:
      - test